<?xml version="1.0" encoding="utf-8"?><Database Name="Chat_DataBase" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\App_Data\Chat_DataBase.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="ChatServer.Properties.Settings" SettingsPropertyName="Chat_DataBaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.USERS" Member="USERs">
    <Type Name="USER">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Password" Type="System.String" DbType="NChar(28) NOT NULL" CanBeNull="false" />
      <Column Name="First_Name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Last_Name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Function Name="dbo.Register" Method="Register">
    <Parameter Name="Username" Parameter="username" Type="System.String" DbType="Text" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="Text" />
    <Parameter Name="First_Name" Parameter="first_Name" Type="System.String" DbType="Text" />
    <Parameter Name="Last_Name" Parameter="last_Name" Type="System.String" DbType="Text" />
    <Return Type="System.Int32" />
  </Function>
</Database>